/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_usp_ime_oppstore_broker_OppStoreBroker */

#ifndef _Included_br_usp_ime_oppstore_broker_OppStoreBroker
#define _Included_br_usp_ime_oppstore_broker_OppStoreBroker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_usp_ime_oppstore_broker_OppStoreBroker
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_usp_ime_oppstore_broker_OppStoreBroker_print
  (JNIEnv *, jobject);

/*
 * Class:     br_usp_ime_oppstore_broker_OppStoreBroker
 * Method:    removeDataW_
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_usp_ime_oppstore_broker_OppStoreBroker_removeDataW_1
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_usp_ime_oppstore_broker_OppStoreBroker
 * Method:    storeFileW_
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_usp_ime_oppstore_broker_OppStoreBroker_storeFileW_1
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_usp_ime_oppstore_broker_OppStoreBroker
 * Method:    retrieveFileW_
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_usp_ime_oppstore_broker_OppStoreBroker_retrieveFileW_1
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
